name: Build and test Snap

on:
  workflow_call:
  workflow_dispatch:

env:
  SNAP_ARTIFACT_NAME: dss-snap

jobs:
  build-snap:
    name: Build the snap
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: snapcore/action-build@v1.2.0
      id: snapcraft
    - uses: actions/upload-artifact@v4
      id: upload-snap-artifact
      with:
        name: ${{ env.SNAP_ARTIFACT_NAME }}
        path: ${{ steps.snapcraft.outputs.snap }}

  test:
    name: Test the snap
    runs-on: ubuntu-22.04
    needs:
      - build-snap
    steps:
    # TODO: Important?
    # - name: Checkout repository
    #   uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      id: download-snap-artifact
      with:
        name: ${{ env.SNAP_ARTIFACT_NAME }}
    - name: Install the snap locally
      run: sudo snap install ${{ steps.download-snap-artifact.outputs.download-path }}

    - name: Set up Microk8s
      uses: balchua/microk8s-actions@v0.3.2
      with:
        channel: '1.28/stable'
        addons: '["hostpath-storage"]'

    - name: Test dss snap
      run: |
        data-science-stack initialize --kubeconfig ~/.kube/config
        data-science-stack create x --image kubeflownotebookswg/jupyter-scipy:v1.8.0 --kubeconfig ~/.kube/config
