name: Build and test Snap

on:
  workflow_call:
  workflow_dispatch:

env:
  SNAP_ARTIFACT_NAME: dss-snap
  SNAP_FILE: dss.snap

jobs:
  build-snap:
    name: Build the snap
    runs-on: ubuntu-22.04
    outputs:
      snap-file: ${{ steps.snapcraft.outputs.snap }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: snapcore/action-build@v1.2.0
      id: snapcraft
      with:
        snapcraft-args: "-o ${{ env.SNAP_FILE }}"
    - uses: actions/upload-artifact@v4
      id: upload-snap-artifact
      with:
        name: ${{ env.SNAP_ARTIFACT_NAME }}
        path: ${{ steps.snapcraft.outputs.snap }}

  test:
    name: Test the snap
    runs-on: ubuntu-22.04
    needs:
      - build-snap
    steps:
    # TODO: Important?
    # - name: Checkout repository
    #   uses: actions/checkout@v4
    - run: echo snap file from previous is ${{ needs.build-snap.outputs.snap-file }}
    - uses: actions/download-artifact@v4
      id: download-snap-artifact
      with:
        name: ${{ env.SNAP_ARTIFACT_NAME }}
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Install the snap locally
      # use --devmode because the snap is strictly confined and we don't have a way to
      # pass a kubeconfig file to a strict snap yet
      # TODO after https://github.com/canonical/data-science-stack/issues/37: Remove --devmode
      # --dangerous so we trust the snap locally
      run: sudo snap install ${{ needs.build-snap.outputs.snap-file }} --dangerous --devmode

    - name: Set up Microk8s
      uses: balchua/microk8s-actions@v0.3.2
      with:
        channel: '1.28/stable'
        addons: '["hostpath-storage"]'

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Test dss snap
      run: |
        data-science-stack.dss initialize --kubeconfig ~/.kube/config
        data-science-stack.dss create x --image kubeflownotebookswg/jupyter-scipy:v1.8.0 --kubeconfig ~/.kube/config
