name: On Pull Request

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # DEBUG: Restore this
  # test-python-lib:
  #   name: Run Tests
  #   uses: ./.github/workflows/tests.yaml

  test-snap:
    name: Build and test Snap
    uses: ./.github/workflows/build_and_test_snap.yaml
