name: Publish to Snapstore

on:
  workflow_call:
    inputs:
      source_branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        default: ''
        required: false
        type: string
      destination_channel:
        description: Snapstore channel to publish to
        required: false
        default: 'latest/edge'
        type: string
    secrets:
      # TODO: Required only if we publish
      SNAPCRAFT_STORE_CREDENTIALS:
        required: true
  workflow_dispatch:
    inputs:
      source_branch:
        description: Github branch from this repo to publish.  If blank, will use the default branch
        required: false
        default: ''
        type: string
      destination_channel:
        description: Snapstore channel to publish to
        required: false
        default: 'latest/edge'
        type: string

env:
  SNAP_ARTIFACT_NAME: dss-snap

jobs:
  build-snap:
    name: Build the snap
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with: 
        # fetch-depth: 0
        ref: ${{ inputs.source_branch }}
    - name: test tag command
      run: |
        git describe --tags --abbrev=10
    - uses: snapcore/action-build@v1.2.0
      id: snapcraft
    - uses: actions/upload-artifact@v4
      id: upload-snap-artifact
      with:
        name: ${{ env.SNAP_ARTIFACT_NAME }}
        path: ${{ steps.snapcraft.outputs.snap }}

  test:
    name: Test the snap
    runs-on: ubuntu-22.04
    needs:
      - build-snap
    steps:
    # TODO: Important?
    # - name: Checkout repository
    #   uses: actions/checkout@v4
    #   with: 
    #     fetch-depth: 0
    #     ref: ${{ inputs.source_branch }}
    - uses: actions/download-artifact@v4
      id: download-snap-artifact
      with:
        name: ${{ env.SNAP_ARTIFACT_NAME }}
    - name: Install the snap locally
      run: sudo snap install ${{ steps.download-snap-artifact.outputs.download-path }}

    - name: Set up Microk8s
      uses: balchua/microk8s-actions@v0.3.2
      with:
        channel: '1.28/stable'
        addons: '["hostpath-storage"]'

    - name: Test dss snap
      run: |
        dss initialize --kubeconfig ~/.kube/config
        dss create x --image kubeflownotebookswg/jupyter-scipy:v1.8.0 --kubeconfig ~/.kube/config

  publish-snap:
    name: Publish to Snapstore
    runs-on: ubuntu-22.04
    needs:
      - build-snap
      - test
    steps:
    - uses: actions/download-artifact@v4
      id: download-snap-artifact
      with:
        name: ${{ env.SNAP_ARTIFACT_NAME }}

    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      with:
        snap: ${{ steps.download-snap-artifact.outputs.download-path }}
        # TODO: Set the release properly
        release: ${{ inputs.destination_channel }}
